version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    env_file: .env
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    ports:
      - 3306:3306
  wordpress:
    image: wordpress:5.2.2-php7.3-apache
    restart: always
    env_file: .env
    depends_on:
      - db
    environment:
      - WORDPRESS_DB_HOST=db
    ports:
      - 8080:80
